/**
 * Keratoscope profile model and deterministic CSS generation.
 *
 * @typedef {object} KeratoscopeProfile
 * @property {number} dx - Horizontal ghost offset in pixels.
 * @property {number} dy - Vertical ghost offset in pixels.
 * @property {number} opacity - Ghost layer opacity (0–1).
 * @property {number} blur - Ghost layer blur radius in pixels.
 * @property {number} fontWeightDelta - Font weight adjustment.
 * @property {number} letterSpacingDelta - Letter spacing adjustment in em.
 */

const PROFILE_VERSION = 1;
const STORAGE_KEY = 'keratoscope_profile_v1';

const DEFAULT_PROFILE = Object.freeze({
  dx: 0,
  dy: 0,
  opacity: 0.35,
  blur: 0,
  fontWeightDelta: 0,
  letterSpacingDelta: 0,
});

const CLAMPS = Object.freeze({
  dx: { min: -8, max: 8 },
  dy: { min: -8, max: 8 },
  opacity: { min: 0, max: 1 },
  blur: { min: 0, max: 4 },
  fontWeightDelta: { min: -100, max: 300 },
  letterSpacingDelta: { min: -0.05, max: 0.15 },
});

/**
 * Clamp a number to an inclusive range.
 *
 * @param {number} value
 * @param {number} min
 * @param {number} max
 * @returns {number}
 */
function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

/**
 * Validate and clamp a raw profile object.
 *
 * @param {unknown} raw
 * @returns {KeratoscopeProfile}
 */
export function normalizeProfile(raw) {
  if (!raw || typeof raw !== 'object') {
    return { ...DEFAULT_PROFILE };
  }

  const input = /** @type {Record<string, unknown>} */ (raw);
  const asNumber = (key) => {
    const value = input[key];
    return typeof value === 'number' && Number.isFinite(value) ? value : DEFAULT_PROFILE[key];
  };

  return {
    dx: clamp(asNumber('dx'), CLAMPS.dx.min, CLAMPS.dx.max),
    dy: clamp(asNumber('dy'), CLAMPS.dy.min, CLAMPS.dy.max),
    opacity: clamp(asNumber('opacity'), CLAMPS.opacity.min, CLAMPS.opacity.max),
    blur: clamp(asNumber('blur'), CLAMPS.blur.min, CLAMPS.blur.max),
    fontWeightDelta: clamp(asNumber('fontWeightDelta'), CLAMPS.fontWeightDelta.min, CLAMPS.fontWeightDelta.max),
    letterSpacingDelta: clamp(asNumber('letterSpacingDelta'), CLAMPS.letterSpacingDelta.min, CLAMPS.letterSpacingDelta.max),
  };
}

/**
 * Generate deterministic CSS from a profile.
 *
 * @param {KeratoscopeProfile} profile
 * @returns {string}
 */
export function generateCSS(profile) {
  const p = normalizeProfile(profile);

  const shadows = [];
  if (p.dx !== 0 || p.dy !== 0 || p.blur > 0) {
    // Cancellation layer: a faint, offset shadow opposite to the perceived ghost.
    shadows.push(`${-p.dx}px ${-p.dy}px ${p.blur}px rgba(0, 0, 0, ${p.opacity.toFixed(3)})`);
  }

  const rules = [
    '/* Keratoscope generated userstyle */',
    '/* This is a presentation tweak, not a medical device. */',
    '/* It may reduce perceived text doubling for some users — no guarantee. */',
    '',
    'p, li, h1, h2, h3, h4, h5, h6, span, div, article, section, blockquote, label, td, th {',
    '  /* Edge emphasis improves perceived edge sharpness for some readers */',
    '  -webkit-font-smoothing: antialiased;',
    '  -moz-osx-font-smoothing: grayscale;',
  ];

  if (shadows.length > 0) {
    rules.push(`  text-shadow: ${shadows.join(', ')};`);
  }
  if (p.fontWeightDelta !== 0) {
    rules.push(`  font-weight: calc(400 + ${p.fontWeightDelta});`);
  }
  if (p.letterSpacingDelta !== 0) {
    rules.push(`  letter-spacing: ${p.letterSpacingDelta.toFixed(4)}em;`);
  }

  rules.push('}');
  return rules.join('\n');
}

/**
 * Export profile as a Stylus-compatible userstyle.
 *
 * @param {KeratoscopeProfile} profile
 * @returns {string}
 */
export function generateUserstyle(profile) {
  const p = normalizeProfile(profile);
  const css = generateCSS(p);
  return [
    '/* ==UserStyle==',
    '@name           Keratoscope Profile',
    '@namespace      github.com/markkirby125/keratoscope',
    '@version        1.0.0',
    '@description    Personal ghosting compensation generated by Keratoscope',
    '@author         Keratoscope user',
    '==/UserStyle== */',
    '',
    '@-moz-document url-prefix("http://"), url-prefix("https://") {',
    ...css.split('\n').map((line) => (line ? `  ${line}` : line)),
    '}',
  ].join('\n');
}

/**
 * Load profile from localStorage.
 *
 * @returns {KeratoscopeProfile}
 */
export function loadProfile() {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (!stored) return { ...DEFAULT_PROFILE };
    return normalizeProfile(JSON.parse(stored));
  } catch {
    return { ...DEFAULT_PROFILE };
  }
}

/**
 * Save profile to localStorage.
 *
 * @param {KeratoscopeProfile} profile
 */
export function saveProfile(profile) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(normalizeProfile(profile)));
  } catch {
    // localStorage may be unavailable or full; fail silently.
  }
}

/**
 * Return the default profile.
 *
 * @returns {KeratoscopeProfile}
 */
export function getDefaultProfile() {
  return { ...DEFAULT_PROFILE };
}

export { PROFILE_VERSION, STORAGE_KEY, DEFAULT_PROFILE };
